//
//  UIColor+BsktAdditions.swift
//
//  Generated by Zeplin on 4/16/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
    class func bsktGreyishColor() -> UIColor {
        return UIColor(white: 178.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktDarkColor() -> UIColor {
        return UIColor(red: 27.0 / 255.0, green: 33.0 / 255.0, blue: 44.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktAlgaeGreenColor() -> UIColor {
        return UIColor(red: 44.0 / 255.0, green: 201.0 / 255.0, blue: 103.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktSalmonColor() -> UIColor {
        return UIColor(red: 249.0 / 255.0, green: 133.0 / 255.0, blue: 103.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktWhiteColor() -> UIColor {
        return UIColor(white: 248.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktWindowsBlueColor() -> UIColor {
        return UIColor(red: 51.0 / 255.0, green: 151.0 / 255.0, blue: 206.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktPastelRedColor() -> UIColor {
        return UIColor(red: 233.0 / 255.0, green: 87.0 / 255.0, blue: 87.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktMutedBlueColor() -> UIColor {
        return UIColor(red: 54.0 / 255.0, green: 100.0 / 255.0, blue: 162.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktGreyishBrownColor() -> UIColor {
        return UIColor(white: 64.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktPaleRedColor() -> UIColor {
        return UIColor(red: 229.0 / 255.0, green: 90.0 / 255.0, blue: 66.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktWarmGreyColor() -> UIColor {
        return UIColor(white: 144.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktCoralColor() -> UIColor {
        return UIColor(red: 244.0 / 255.0, green: 73.0 / 255.0, blue: 73.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktBlueGreyColor() -> UIColor {
        return UIColor(red: 93.0 / 255.0, green: 106.0 / 255.0, blue: 132.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktWhite75Color() -> UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 0.75)
    }
    
    class func bsktWhite2Color() -> UIColor {
        return UIColor(white: 234.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktGreyishTwoColor() -> UIColor {
        return UIColor(white: 176.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktDenimBlueColor() -> UIColor {
        return UIColor(red: 57.0 / 255.0, green: 87.0 / 255.0, blue: 155.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktBrownishGreyColor() -> UIColor {
        return UIColor(white: 96.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktWarmGreyTwoColor() -> UIColor {
        return UIColor(white: 160.0 / 255.0, alpha: 1.0)
    }
    
    class func bsktWhiteTwoColor() -> UIColor {
        return UIColor(white: 224.0 / 255.0, alpha: 1.0)
    }
}
