//
//  UIFont+BsktAdditions.swift
//
//  Generated by Zeplin on 4/16/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
    class func bsktBiggestBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-DemiBold", size: 32.0)
    }

    class func bsktHugeDemiBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-DemiBold", size: 27.0)
    }
    
    class func bsktEmojiMediumFont() -> UIFont? {
        return UIFont(name: "AppleColorEmoji", size: 24.0)
    }

    class func bsktBigBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-DemiBold", size: 16.0)
    }
    
    class func bsktMediumBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-DemiBold", size: 14.0)
    }
    
    class func bsktBiggerMediumFont() -> UIFont? {
        return UIFont(name: "AvenirNext-Medium", size: 17.0)
    }
    
    class func bsktBiggerRegularFont() -> UIFont? {
        return UIFont(name: "AvenirNext-Regular", size: 17.0)
    }
    
    class func bsktMediumMediumFont() -> UIFont? {
        return UIFont(name: "AvenirNext-Medium", size: 14.0)
    }
    
    class func bsktSmallishBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-DemiBold", size: 13.0)
    }
    
    class func bsktSmallishMediumFont() -> UIFont? {
        return UIFont(name: "AvenirNext-Medium", size: 13.0)
    }
    
    class func bsktSmallMediumFont() -> UIFont? {
        return UIFont(name: "AvenirNext-Medium", size: 11.0)
    }
    
    class func bsktSmallBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-Bold", size: 10.0)
    }
    
    class func bsktSmallishRegularFont() -> UIFont? {
        return UIFont(name: "AvenirNext-Regular", size: 13.0)
    }
    
    class func bsktSmallerBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-DemiBold", size: 12.0)
    }

    class func bsktBiggerBoldFont() -> UIFont? {
        return UIFont(name: "AvenirNext-DemiBold", size: 18.0)
    }

    class func bsktBigMediumFont() -> UIFont {
        return UIFont(name: "AvenirNext-Medium", size: 16.0)!
    }
}
